//! M09-020 — seal the two non-reproducible baseline checkpoints as bounded fixtures.
//!
//! Training is stochastic across threads, so `out/stage2_r6/final10000.json` and
//! `out/stage1_hacanclone/frozen5000.json` cannot be regenerated (MLP plan §10). This tool
//! deterministically compresses exactly those two files with a pinned single-threaded zstd
//! encoder into `fixtures/mlp-baselines/`, records raw and compressed sha256, sizes, tool
//! version/settings, license/provenance, and the extraction command in
//! `fixtures/mlp-baselines/manifest.json`.
//!
//! Fail-closed discipline:
//! - input checksums must match the durable manifest before anything is written;
//! - each input is compressed twice and the results compared — any nondeterminism aborts;
//! - combined compressed size must be ≤ 50 MiB or nothing is written;
//! - an existing fixture that differs from what would be produced is refused (no silent
//!   overwrite of a sealed artifact).
//!
//! Usage: `cargo run --release -p ti4-sim --example seal_baselines`

use std::fs;
use std::path::{Path, PathBuf};

use sha2::{Digest, Sha256};
use zstd::encode_all;

/// Pinned compression settings (recorded in the fixture manifest).
const ZSTD_LEVEL: i32 = 19;
/// MLP plan §10 cap on combined compressed fixture size.
const MAX_COMBINED_COMPRESSED: u64 = 50 * 1024 * 1024;

#[derive(Clone, Copy)]
struct Input {
    /// Raw path (gitignored local artifact).
    raw_path: &'static str,
    /// Durable-manifest sha256 of the raw bytes.
    expected_raw_sha256: &'static str,
    /// Fixture file name under `fixtures/mlp-baselines/`.
    fixture_name: &'static str,
}

const INPUTS: [Input; 2] = [
    Input {
        raw_path: "out/stage2_r6/final10000.json",
        expected_raw_sha256: "be792a2a207ced25d589162d875bae4fb1f320c8e5637045486db6a24ce5b55b",
        fixture_name: "final10000.zst",
    },
    Input {
        raw_path: "out/stage1_hacanclone/frozen5000.json",
        expected_raw_sha256: "0d0fa9e5d7a3f9ce848ef2c52a4a4144183af7ca5c15082850874a18c039ca4a",
        fixture_name: "frozen5000.zst",
    },
];

struct Sealed {
    input: Input,
    raw_sha256: String,
    raw_size: usize,
    compressed: Vec<u8>,
}

fn main() -> Result<(), String> {
    let out_dir = Path::new("fixtures/mlp-baselines");

    // Phase 1 — verify identities and compress (fail closed before any write).
    let mut sealed: Vec<Sealed> = Vec::with_capacity(INPUTS.len());
    for input in &INPUTS {
        let bytes = fs::read(input.raw_path)
            .map_err(|error| format!("read {}: {error}", input.raw_path))?;
        let raw_sha256 = hex(&Sha256::digest(&bytes));
        if raw_sha256 != input.expected_raw_sha256 {
            return Err(format!(
                "raw checksum mismatch for {}: expected {}, found {} — refusing to seal",
                input.raw_path, input.expected_raw_sha256, raw_sha256
            ));
        }

        // Determinism self-check: compress twice, require byte identity.
        let first = encode_all(bytes.as_slice(), ZSTD_LEVEL)
            .map_err(|error| format!("zstd pass 1 on {}: {error}", input.raw_path))?;
        let second = encode_all(bytes.as_slice(), ZSTD_LEVEL)
            .map_err(|error| format!("zstd pass 2 on {}: {error}", input.raw_path))?;
        if first != second {
            return Err(format!(
                "nondeterministic compression of {} — refusing to seal",
                input.raw_path
            ));
        }

        sealed.push(Sealed {
            input: *input,
            raw_sha256,
            raw_size: bytes.len(),
            compressed: first,
        });
    }

    let combined_compressed: u64 = sealed
        .iter()
        .map(|sealed| u64::try_from(sealed.compressed.len()).unwrap_or(u64::MAX))
        .sum();
    if combined_compressed > MAX_COMBINED_COMPRESSED {
        return Err(format!(
            "combined compressed size {combined_compressed} exceeds the 50 MiB cap — stopping \
             for P3 authority (external durable archive)"
        ));
    }

    // Phase 2 — write fixtures and manifest.
    write_fixtures(&sealed, out_dir, combined_compressed)
}

fn write_fixtures(
    sealed: &[Sealed],
    out_dir: &Path,
    combined_compressed: u64,
) -> Result<(), String> {
    fs::create_dir_all(out_dir).map_err(|error| error.to_string())?;
    let mut entries = Vec::with_capacity(sealed.len());
    for sealed in sealed {
        let fixture_path: PathBuf = out_dir.join(sealed.input.fixture_name);
        if let Ok(existing) = fs::read(&fixture_path)
            && existing != sealed.compressed
        {
            return Err(format!(
                "existing sealed fixture {} differs from regenerated bytes — \
                 refusing to overwrite a sealed artifact",
                fixture_path.display()
            ));
        }
        fs::write(&fixture_path, &sealed.compressed).map_err(|error| error.to_string())?;

        entries.push(serde_json::json!({
            "fixture": format!("fixtures/mlp-baselines/{}", sealed.input.fixture_name),
            "raw_path": sealed.input.raw_path,
            "raw_sha256": sealed.raw_sha256,
            "compressed_sha256": hex(&Sha256::digest(&sealed.compressed)),
            "raw_size_bytes": sealed.raw_size,
            "compressed_size_bytes": sealed.compressed.len(),
        }));
    }

    let manifest = serde_json::json!({
        "schema": "ti4-mlp-baselines-v1",
        "package": "M09-020",
        "policy": {
            "cap_combined_compressed_bytes": MAX_COMBINED_COMPRESSED,
            "compression": {
                "tool": format!("zstd crate {} (single-threaded encode_all)", zstd_version()),
                "level": ZSTD_LEVEL,
                "threads": 1,
            },
        },
        "provenance": {
            "content": "This repository's own training outputs (no third-party content).",
            "stage2_r6": "Stage-2 r6 run, completed checkpoint at update 10000.",
            "stage1_hacanclone": "Stage-1 hacan clone run, frozen checkpoint at update 5000.",
            "licenses": {
                "rust_wrapper_chain": [
                    {"crate": "zstd", "version": "0.13.3", "license": "MIT"},
                    {"crate": "zstd-safe", "version": "7.2.4", "license": "MIT OR Apache-2.0"},
                    {
                        "crate": "zstd-sys",
                        "version": "2.0.16+zstd.1.5.7",
                        "license": "MIT/Apache-2.0"
                    }
                ],
                "bundled_native_library": "upstream zstd 1.5.7 (BSD-3-Clause), bundled by zstd-sys",
                "content_note": "fixtures contain only repository-generated data",
            },
        },
        "extraction": {
            "command_zstd_cli": [
                "zstd -d fixtures/mlp-baselines/final10000.zst -o out/stage2_r6/final10000.json",
                "zstd -d fixtures/mlp-baselines/frozen5000.zst -o out/stage1_hacanclone/frozen5000.json",
            ],
            "command_seal_tool": "cargo run --release -p ti4-sim --example seal_baselines (re-seals from raw inputs; refuses on any mismatch)",
        },
        "entries": entries,
    });

    fs::write(
        out_dir.join("manifest.json"),
        serde_json::to_string_pretty(&manifest).unwrap() + "\n",
    )
    .map_err(|error| error.to_string())?;

    for sealed in sealed {
        println!(
            "sealed fixtures/mlp-baselines/{} ({} bytes -> {} bytes)",
            sealed.input.fixture_name,
            sealed.raw_size,
            sealed.compressed.len()
        );
    }
    println!("combined compressed: {combined_compressed} bytes (cap 52428800)");
    Ok(())
}

fn zstd_version() -> &'static str {
    // Pinned by Cargo.lock; the manifest records it so extraction is reproducible.
    "0.13.3"
}

fn hex(digest: &[u8]) -> String {
    use std::fmt::Write as _;
    let mut out = String::with_capacity(digest.len() * 2);
    for byte in digest {
        let _ = write!(out, "{byte:02x}");
    }
    out
}
