//! Verify the pinned libtorch against its committed manifest, then stage its DLLs.
//!
//! # Why verification lives here
//!
//! M09-025 committed a SHA-256 manifest and pointed `LIBTORCH` at a gitignored directory — and
//! nothing checked one against the other (F-M09-025-1). A changed `out/libtorch-2.9.1-cpu` would
//! have been linked while every committed checksum stayed green, which is not a pin; it is a
//! filename. The manifest is now a gate: every binary that gets linked, and both licence files,
//! must match it or the build fails.
//!
//! # Why staging is not a filename check
//!
//! Windows resolves a dependent DLL from the executable's own directory before it consults `PATH`,
//! so the DLLs are placed beside the test binaries — otherwise every `cargo test` needs
//! `%LIBTORCH%\lib` exported first and the workspace gate stops running from a clean checkout.
//! An earlier version skipped any same-named file already present, so a stale DLL from a previous
//! pin kept being loaded. Staging now compares content and replaces on mismatch.
//!
//! Hard links where the filesystem allows them: `out/` and `target/` are one volume, so the 266 MB
//! costs no disk. A copy is the fallback.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

/// Where the committed manifests live, relative to this crate.
const MANIFEST_DIR: &str = "../../plans/artifacts";

/// One real symbol from `torch_cuda`, forced into the link of every binary this crate produces.
///
/// # Why a binary needs this at all
///
/// `torch-sys` passes `torch_cuda.lib` to the linker, but MSVC drops an import nothing references,
/// and `/WHOLEARCHIVE` only produces an import descriptor with no function thunks — which the
/// Windows loader skips. Measured directly: with the descriptor present and no thunk, the process
/// loaded `c10.dll`, `torch_cpu.dll` and `cudart64_12.dll` but **not** `torch_cuda.dll`.
///
/// `torch_cuda`'s static initialiser is what registers CUDA with `torch_cpu`, so without the DLL
/// loaded `torch::cuda::device_count()` is 0 and CUDA looks absent on a machine that has it.
/// Forcing one genuine symbol creates a real thunk, so the loader brings the DLL in.
///
/// `at::cuda::warp_size()` is the choice because it takes no arguments, returns an `int`, and is
/// not going to be renamed.
const CUDA_ANCHOR: &str = "?warp_size@cuda@at@@YAHXZ";

/// The committed manifest for the distribution `LIBTORCH` points at.
///
/// Derived from the directory's own name rather than hardcoded: M10-037 adds a second distribution,
/// and verifying one while linking the other would report a clean gate over the wrong bytes.
fn manifest_for(root: &Path) -> String {
    let name = root
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or_default();
    format!("{MANIFEST_DIR}/{name}.manifest.json")
}

fn fail(message: &str) -> ! {
    println!("cargo:warning={message}");
    eprintln!("{message}");
    std::process::exit(1);
}

fn sha256(path: &Path) -> Result<String, std::io::Error> {
    use sha2::Digest;
    let bytes = std::fs::read(path)?;
    let mut hasher = sha2::Sha256::new();
    hasher.update(&bytes);
    Ok(format!("{:x}", hasher.finalize()))
}

/// `{"pinned_files": [{"path": .., "sha256": .., "bytes": ..}, ..]}`, without a JSON dependency.
///
/// The manifest is generated by this project and its shape is fixed; a hand-rolled scan keeps
/// `build.rs` free of dependencies that would themselves need pinning.
fn pinned_files(text: &str) -> BTreeMap<String, String> {
    let mut pinned = BTreeMap::new();
    let mut path: Option<String> = None;
    for raw in text.lines() {
        let line = raw.trim().trim_end_matches(',');
        if let Some(value) = line.strip_prefix("\"path\":") {
            path = Some(value.trim().trim_matches('"').to_owned());
        } else if let (Some(value), Some(key)) = (line.strip_prefix("\"sha256\":"), path.take()) {
            pinned.insert(key, value.trim().trim_matches('"').to_owned());
        }
    }
    pinned
}

fn compiler_version() -> String {
    let rustc = std::env::var_os("RUSTC").unwrap_or_else(|| "rustc".into());
    std::process::Command::new(rustc)
        .arg("--version")
        .output()
        .ok()
        .filter(|output| output.status.success())
        .and_then(|output| String::from_utf8(output.stdout).ok())
        .map(|version| version.trim().to_owned())
        .filter(|version| !version.is_empty())
        .unwrap_or_else(|| fail("could not determine the rustc version for bundle provenance"))
}

fn main() {
    println!("cargo:rustc-env=TI4_RUSTC_VERSION={}", compiler_version());

    println!("cargo:rerun-if-env-changed=LIBTORCH");

    let Ok(libtorch) = std::env::var("LIBTORCH") else {
        // Nothing to verify or stage; `torch-sys` produces the real diagnostic.
        return;
    };
    let root = PathBuf::from(&libtorch);

    let manifest = manifest_for(&root);
    println!("cargo:rerun-if-changed={manifest}");
    let manifest_text = match std::fs::read_to_string(&manifest) {
        Ok(text) => text,
        Err(error) => fail(&format!(
            "no pinned manifest for {}: {manifest} unreadable ({error}). Every libtorch \
             distribution this project links needs its own committed manifest.",
            root.display()
        )),
    };

    // A CUDA distribution needs one real symbol reference in every binary, or the DLL that
    // registers CUDA never loads. Emitted for the final artifacts only: a build script that does
    // not link torch would fail on an unresolved symbol, which is what putting this in RUSTFLAGS
    // does.
    if root.join("lib").join("torch_cuda.dll").is_file() {
        // Only the target kinds this crate actually has: cargo rejects an instruction naming a
        // kind with no targets, so `bins` and `benches` are omitted rather than harmless.
        for target in ["examples", "tests"] {
            println!("cargo:rustc-link-arg-{target}=/INCLUDE:{CUDA_ANCHOR}");
        }
    }
    let pinned = pinned_files(&manifest_text);
    if pinned.is_empty() {
        fail("pinned libtorch manifest lists no files; refusing to link an unverified libtorch");
    }

    // Tell Cargo to rerun whenever any usable libtorch byte can change. Emitting this only for the
    // manifest meant that once the crate was up to date, editing a pinned DLL or dropping an extra
    // one into `lib/` did not rerun the verifier, and the next ordinary `cargo test` linked the
    // changed bytes with the gate skipped (F-M09-025-5). The earlier mutation check passed only
    // because touching `build.rs` forced a rebuild — it never exercised the incremental path.
    //
    // The directory itself is tracked as well as each file, so an *addition* or a removal is caught
    // and not only a modification.
    println!("cargo:rerun-if-changed={}", root.join("lib").display());
    for relative in pinned.keys() {
        println!("cargo:rerun-if-changed={}", root.join(relative).display());
    }

    // 1. Verify every pinned file against the manifest, before anything is linked or staged.
    for (relative, expected) in &pinned {
        let path = root.join(relative);
        match sha256(&path) {
            Ok(actual) if &actual == expected => {}
            Ok(actual) => fail(&format!(
                "pinned libtorch file {relative} is {actual}, manifest says {expected}. \
                 The pin is the bytes, not the path: restore the pinned copy or re-pin deliberately."
            )),
            Err(error) => fail(&format!(
                "pinned libtorch file {relative} could not be read ({error}). \
                 Reproduce it with the recipe in plans/evidence/M09-025.md."
            )),
        }
    }

    // 2. Every DLL that will be linked must be one the manifest pins. An unpinned binary in the
    //    directory is not a stray file to ignore — it is a library that could be loaded.
    let lib = root.join("lib");
    let entries = match std::fs::read_dir(&lib) {
        Ok(entries) => entries,
        Err(error) => fail(&format!(
            "pinned libtorch lib directory {} unreadable: {error}",
            lib.display()
        )),
    };
    let out = PathBuf::from(std::env::var("OUT_DIR").expect("cargo sets OUT_DIR"));
    let Some(profile_dir) = out.ancestors().nth(3).map(Path::to_path_buf) else {
        fail("cannot locate the target profile directory from OUT_DIR");
    };
    let deps = profile_dir.join("deps");

    for entry in entries {
        let entry = match entry {
            Ok(entry) => entry,
            Err(error) => fail(&format!("reading the pinned lib directory: {error}")),
        };
        let path = entry.path();
        if path.extension().is_none_or(|ext| ext != "dll") {
            continue;
        }
        let Some(name) = path.file_name().and_then(|n| n.to_str()).map(str::to_owned) else {
            continue;
        };
        let key = format!("lib/{name}");
        if !pinned.contains_key(&key) {
            fail(&format!(
                "{key} is present in the pinned libtorch but absent from the manifest; \
                 refusing to stage an unpinned library"
            ));
        }
        let expected = &pinned[&key];

        // 3. Stage by content, not by filename. A same-named file left by an earlier pin is stale,
        //    not equivalent.
        for directory in [profile_dir.as_path(), deps.as_path()] {
            let target = directory.join(&name);
            if let Ok(staged) = sha256(&target) {
                if &staged == expected {
                    continue;
                }
                if let Err(error) = std::fs::remove_file(&target) {
                    fail(&format!(
                        "stale staged {name} could not be replaced: {error}"
                    ));
                }
            }
            if let Err(error) = std::fs::create_dir_all(directory) {
                fail(&format!("cannot create {}: {error}", directory.display()));
            }
            if std::fs::hard_link(&path, &target).is_err()
                && let Err(error) = std::fs::copy(&path, &target)
            {
                fail(&format!("cannot stage {name}: {error}"));
            }
        }
    }
}
