//! Verify the pinned libtorch against its committed manifest, then stage its DLLs.
//!
//! # Why verification lives here
//!
//! M09-025 committed a SHA-256 manifest and pointed `LIBTORCH` at a gitignored directory — and
//! nothing checked one against the other (F-M09-025-1). A changed `out/libtorch-2.9.1-cpu` would
//! have been linked while every committed checksum stayed green, which is not a pin; it is a
//! filename. The manifest is now a gate: every binary that gets linked, and both licence files,
//! must match it or the build fails.
//!
//! # Why staging is not a filename check
//!
//! Windows resolves a dependent DLL from the executable's own directory before it consults `PATH`,
//! so the DLLs are placed beside the test binaries — otherwise every `cargo test` needs
//! `%LIBTORCH%\lib` exported first and the workspace gate stops running from a clean checkout.
//! An earlier version skipped any same-named file already present, so a stale DLL from a previous
//! pin kept being loaded. Staging now compares content and replaces on mismatch.
//!
//! Hard links where the filesystem allows them: `out/` and `target/` are one volume, so the 266 MB
//! costs no disk. A copy is the fallback.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

/// Where the committed manifest lives, relative to this crate.
const MANIFEST: &str = "../../plans/artifacts/libtorch-2.9.1-cpu.manifest.json";

fn fail(message: &str) -> ! {
    println!("cargo:warning={message}");
    eprintln!("{message}");
    std::process::exit(1);
}

fn sha256(path: &Path) -> Result<String, std::io::Error> {
    use sha2::Digest;
    let bytes = std::fs::read(path)?;
    let mut hasher = sha2::Sha256::new();
    hasher.update(&bytes);
    Ok(format!("{:x}", hasher.finalize()))
}

/// `{"pinned_files": [{"path": .., "sha256": .., "bytes": ..}, ..]}`, without a JSON dependency.
///
/// The manifest is generated by this project and its shape is fixed; a hand-rolled scan keeps
/// `build.rs` free of dependencies that would themselves need pinning.
fn pinned_files(text: &str) -> BTreeMap<String, String> {
    let mut pinned = BTreeMap::new();
    let mut path: Option<String> = None;
    for raw in text.lines() {
        let line = raw.trim().trim_end_matches(',');
        if let Some(value) = line.strip_prefix("\"path\":") {
            path = Some(value.trim().trim_matches('"').to_owned());
        } else if let (Some(value), Some(key)) = (line.strip_prefix("\"sha256\":"), path.take()) {
            pinned.insert(key, value.trim().trim_matches('"').to_owned());
        }
    }
    pinned
}

fn main() {
    println!("cargo:rerun-if-env-changed=LIBTORCH");
    println!("cargo:rerun-if-changed={MANIFEST}");

    let Ok(libtorch) = std::env::var("LIBTORCH") else {
        // Nothing to verify or stage; `torch-sys` produces the real diagnostic.
        return;
    };
    let root = PathBuf::from(&libtorch);

    let manifest_text = match std::fs::read_to_string(MANIFEST) {
        Ok(text) => text,
        Err(error) => fail(&format!(
            "pinned libtorch manifest {MANIFEST} unreadable: {error}"
        )),
    };
    let pinned = pinned_files(&manifest_text);
    if pinned.is_empty() {
        fail("pinned libtorch manifest lists no files; refusing to link an unverified libtorch");
    }

    // Tell Cargo to rerun whenever any usable libtorch byte can change. Emitting this only for the
    // manifest meant that once the crate was up to date, editing a pinned DLL or dropping an extra
    // one into `lib/` did not rerun the verifier, and the next ordinary `cargo test` linked the
    // changed bytes with the gate skipped (F-M09-025-5). The earlier mutation check passed only
    // because touching `build.rs` forced a rebuild — it never exercised the incremental path.
    //
    // The directory itself is tracked as well as each file, so an *addition* or a removal is caught
    // and not only a modification.
    println!("cargo:rerun-if-changed={}", root.join("lib").display());
    for relative in pinned.keys() {
        println!("cargo:rerun-if-changed={}", root.join(relative).display());
    }

    // 1. Verify every pinned file against the manifest, before anything is linked or staged.
    for (relative, expected) in &pinned {
        let path = root.join(relative);
        match sha256(&path) {
            Ok(actual) if &actual == expected => {}
            Ok(actual) => fail(&format!(
                "pinned libtorch file {relative} is {actual}, manifest says {expected}. \
                 The pin is the bytes, not the path: restore the pinned copy or re-pin deliberately."
            )),
            Err(error) => fail(&format!(
                "pinned libtorch file {relative} could not be read ({error}). \
                 Reproduce it with the recipe in plans/evidence/M09-025.md."
            )),
        }
    }

    // 2. Every DLL that will be linked must be one the manifest pins. An unpinned binary in the
    //    directory is not a stray file to ignore — it is a library that could be loaded.
    let lib = root.join("lib");
    let entries = match std::fs::read_dir(&lib) {
        Ok(entries) => entries,
        Err(error) => fail(&format!(
            "pinned libtorch lib directory {} unreadable: {error}",
            lib.display()
        )),
    };
    let out = PathBuf::from(std::env::var("OUT_DIR").expect("cargo sets OUT_DIR"));
    let Some(profile_dir) = out.ancestors().nth(3).map(Path::to_path_buf) else {
        fail("cannot locate the target profile directory from OUT_DIR");
    };
    let deps = profile_dir.join("deps");

    for entry in entries {
        let entry = match entry {
            Ok(entry) => entry,
            Err(error) => fail(&format!("reading the pinned lib directory: {error}")),
        };
        let path = entry.path();
        if path.extension().is_none_or(|ext| ext != "dll") {
            continue;
        }
        let Some(name) = path.file_name().and_then(|n| n.to_str()).map(str::to_owned) else {
            continue;
        };
        let key = format!("lib/{name}");
        if !pinned.contains_key(&key) {
            fail(&format!(
                "{key} is present in the pinned libtorch but absent from the manifest; \
                 refusing to stage an unpinned library"
            ));
        }
        let expected = &pinned[&key];

        // 3. Stage by content, not by filename. A same-named file left by an earlier pin is stale,
        //    not equivalent.
        for directory in [profile_dir.as_path(), deps.as_path()] {
            let target = directory.join(&name);
            if let Ok(staged) = sha256(&target) {
                if &staged == expected {
                    continue;
                }
                if let Err(error) = std::fs::remove_file(&target) {
                    fail(&format!(
                        "stale staged {name} could not be replaced: {error}"
                    ));
                }
            }
            if let Err(error) = std::fs::create_dir_all(directory) {
                fail(&format!("cannot create {}: {error}", directory.display()));
            }
            if std::fs::hard_link(&path, &target).is_err()
                && let Err(error) = std::fs::copy(&path, &target)
            {
                fail(&format!("cannot stage {name}: {error}"));
            }
        }
    }
}
