[package]
name = "ti4-mlp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
ti4-tensor.workspace = true
ti4-policy.workspace = true
ti4-engine.workspace = true
ti4-model.workspace = true
ti4-content.workspace = true
rand.workspace = true
rand_chacha.workspace = true
tch.workspace = true
thiserror.workspace = true

[build-dependencies]
sha2.workspace = true

[dev-dependencies]
ti4-sim.workspace = true
serde_json.workspace = true

[lints]
workspace = true
