//! Can the representation tell a choice's options apart at all?
//!
//! The hardest possible capacity question, and the one that needs no teacher, no training and no
//! authored policy to answer: **if two options of a choice carry identical feature vectors, then
//! no weight vector can ever prefer one to the other.** Not "this optimiser did not find it" —
//! no function of these features can, because the features do not distinguish the options. The
//! policy is pinned to a coin flip between them for the rest of time.
//!
//! That makes this a lower bound on the plateau that is independent of everything else: of the
//! learning rule, of the reward, of how long a run goes on. Whatever fraction of decisions is
//! indistinguishable is a fraction the policy can never improve.
//!
//! # What is reported
//!
//! Per decision head, over positions generated by the **learned champion playing itself** — no
//! heuristic anywhere in the loop:
//!
//! - **blind** — decisions holding at least two options with identical feature vectors. On these
//!   the policy is choosing at random among the tied group, however well trained it is.
//! - **tied share** — of all options, the share sitting in a tied group.
//! - **ceiling** — the best top-1 agreement any weight vector could reach against a perfect
//!   teacher, given the ties: a tied group of `k` options can be got right at most `1/k` of the
//!   time. A head at 1.00 is fully separable; a head at 0.50 cannot be more than a coin flip.
//! - **distinct** — mean number of feature slots on which two options of the same choice differ.
//!   One or two means the policy is deciding on almost nothing even where it can decide at all.
//!
//! ```text
//! cargo run -p ti4-training --example separability --release -- --checkpoint out/run_pure_u5000.json --games 40
//! ```

#![expect(
    clippy::cast_precision_loss,
    reason = "decision and option counts are small integers"
)]

use std::collections::BTreeMap;
use std::path::PathBuf;
use std::sync::Arc;

use ti4_content::ContentStore;
use ti4_engine::choice::{Choice, ChoiceOption, Decider, IllegalChoice, Observed};
use ti4_engine::opening::DEFAULT_REQUIREMENT;
use ti4_model::content_types::FULL;
use ti4_model::id::{FactionId, PlayerId};
use ti4_policy::features::{FeatureVector, explicit_choice_features};
use ti4_policy::inference::LearnedBot;
use ti4_policy::learned::{Profile, decision_head};
use ti4_training::rollout::{Horizon, OpeningMap, play_with_deciders};

const FACTIONS: [&str; 6] = ["sol", "letnev", "xxcha", "hacan", "jolnar", "l1z1x"];

fn number(name: &str, fallback: usize) -> usize {
    let args: Vec<String> = std::env::args().collect();
    args.iter()
        .position(|argument| argument == name)
        .and_then(|index| args.get(index + 1))
        .and_then(|value| value.parse().ok())
        .unwrap_or(fallback)
}

fn path_argument(name: &str) -> Option<PathBuf> {
    let args: Vec<String> = std::env::args().collect();
    args.iter()
        .position(|argument| argument == name)
        .and_then(|index| args.get(index + 1))
        .map(PathBuf::from)
}

/// What one head's decisions looked like in feature space.
#[derive(Default)]
struct Tally {
    decisions: usize,
    blind_decisions: usize,
    options: usize,
    tied_options: usize,
    /// Σ over decisions of the best achievable top-1 rate given the ties.
    ceiling: f64,
    /// Σ over compared pairs of the number of slots on which they differ.
    distinct: f64,
    pairs: usize,
}

/// A learned bot that measures every choice it is shown before answering.
struct Watcher {
    inner: LearnedBot,
    tally: Arc<std::sync::Mutex<BTreeMap<String, Tally>>>,
}

/// How many slots two vectors disagree on.
fn differing(left: &FeatureVector, right: &FeatureVector) -> usize {
    let mut count = 0;
    for (key, value) in left {
        if right.get(key) != Some(value) {
            count += 1;
        }
    }
    for (key, _) in right {
        if left.get(key).is_none() {
            count += 1;
        }
    }
    count
}

impl Decider for Watcher {
    fn choose(&mut self, choice: &Choice) -> Result<ChoiceOption, IllegalChoice> {
        self.inner.choose(choice)
    }

    fn choose_seeing(
        &mut self,
        choice: &Choice,
        seen: &Observed<'_>,
    ) -> Result<ChoiceOption, IllegalChoice> {
        if choice.options.len() > 1 {
            let vectors = explicit_choice_features(seen, choice, &choice.player);
            // Group identical vectors. Option counts are tiny, so the quadratic pass is fine and
            // avoids needing a hash of a whole vector.
            let mut group = vec![usize::MAX; vectors.len()];
            let mut groups = 0usize;
            for index in 0..vectors.len() {
                if group[index] != usize::MAX {
                    continue;
                }
                group[index] = groups;
                for other in index + 1..vectors.len() {
                    if group[other] == usize::MAX && vectors[other] == vectors[index] {
                        group[other] = groups;
                    }
                }
                groups += 1;
            }
            let mut sizes = vec![0usize; groups];
            for slot in &group {
                sizes[*slot] += 1;
            }
            let tied: usize = sizes.iter().filter(|size| **size > 1).sum();
            // Best achievable top-1: a tied group of k can be got right at most 1/k of the time,
            // so the ceiling is (number of groups) / (number of options).
            let ceiling = groups as f64 / vectors.len() as f64;
            let mut distinct = 0.0;
            let mut pairs = 0usize;
            for index in 0..vectors.len() {
                for other in index + 1..vectors.len() {
                    distinct += differing(&vectors[index], &vectors[other]) as f64;
                    pairs += 1;
                }
            }

            let mut table = self.tally.lock().expect("tally poisoned");
            let row = table.entry(decision_head(choice).to_owned()).or_default();
            row.decisions += 1;
            row.blind_decisions += usize::from(tied > 0);
            row.options += vectors.len();
            row.tied_options += tied;
            row.ceiling += ceiling;
            row.distinct += distinct;
            row.pairs += pairs;
        }
        self.inner.choose_seeing(choice, seen)
    }
}

fn main() -> Result<(), String> {
    let games = number("--games", 40);
    let content = ContentStore::embedded();
    let path = path_argument("--checkpoint")
        .ok_or_else(|| "need --checkpoint <trained profiles>".to_owned())?;
    let document: serde_json::Value = serde_json::from_slice(
        &std::fs::read(&path).map_err(|error| format!("read {}: {error}", path.display()))?,
    )
    .map_err(|error| format!("parse: {error}"))?;
    let table = document
        .get("profiles")
        .or_else(|| document.get("accepted"))
        .ok_or_else(|| "checkpoint has neither profiles nor accepted".to_owned())?;
    let loaded: BTreeMap<FactionId, Profile> =
        serde_json::from_value(table.clone()).map_err(|error| format!("profiles: {error}"))?;

    let players: Vec<PlayerId> = (0..6).map(|i| PlayerId::new(format!("seat{i}"))).collect();
    let factions: BTreeMap<PlayerId, FactionId> = players
        .iter()
        .cloned()
        .zip(FACTIONS.iter().map(|f| FactionId::new(*f)))
        .collect();
    let shared: BTreeMap<FactionId, Arc<Profile>> = loaded
        .into_iter()
        .map(|(faction, profile)| (faction, Arc::new(profile)))
        .collect();

    let tally = Arc::new(std::sync::Mutex::new(BTreeMap::<String, Tally>::new()));
    println!("the learned champion playing itself over {games} games...");
    for seed in 0..games as u64 {
        let deciders: BTreeMap<PlayerId, Box<dyn Decider>> = players
            .iter()
            .enumerate()
            .map(|(index, player)| {
                let profile = shared[&factions[player]].clone();
                let bot = Watcher {
                    inner: LearnedBot::from_shared(profile, seed * 1_000_003 + index as u64),
                    tally: Arc::clone(&tally),
                };
                (player.clone(), Box::new(bot) as Box<dyn Decider>)
            })
            .collect();
        let rollout = play_with_deciders(
            content,
            &players,
            &factions,
            FULL,
            seed,
            Horizon::rounds(4),
            DEFAULT_REQUIREMENT,
            &OpeningMap::RustVaried,
            deciders,
        );
        if let Some(error) = &rollout.error {
            eprintln!("  seed {seed}: {error}");
        }
    }

    let table = tally.lock().expect("tally poisoned");
    println!(
        "\n{:<14} {:>9} {:>9} {:>10} {:>9} {:>9}",
        "head", "decisions", "blind", "tied opts", "ceiling", "distinct"
    );
    let (mut total_decisions, mut blind, mut ceiling, mut options, mut tied) = (0, 0, 0.0, 0, 0);
    let mut rows: Vec<(&String, &Tally)> = table.iter().collect();
    rows.sort_by_key(|(_, row)| std::cmp::Reverse(row.decisions));
    for (head, row) in rows {
        println!(
            "{head:<14} {:>9} {:>8.1}% {:>9.1}% {:>9.3} {:>9.1}",
            row.decisions,
            100.0 * row.blind_decisions as f64 / row.decisions as f64,
            100.0 * row.tied_options as f64 / row.options as f64,
            row.ceiling / row.decisions as f64,
            row.distinct / row.pairs.max(1) as f64,
        );
        total_decisions += row.decisions;
        blind += row.blind_decisions;
        ceiling += row.ceiling;
        options += row.options;
        tied += row.tied_options;
    }
    println!(
        "\npooled: {total_decisions} decisions, {:.1}% blind, {:.1}% of options tied, ceiling {:.3}",
        100.0 * blind as f64 / total_decisions as f64,
        100.0 * tied as f64 / options as f64,
        ceiling / total_decisions as f64,
    );
    println!(
        "\nA blind decision is one the policy cannot ever get right better than by guessing,\n\
         because the options it is choosing between are identical in feature space. No optimiser,\n\
         reward or run length changes that; only the features can."
    );
    Ok(())
}
