//! In-memory deterministic recovery replay runner for game sessions.

use std::collections::VecDeque;
use thiserror::Error;
use ti4_content::ContentStore;
use ti4_content::galaxy::Galaxy;
use ti4_engine::choice::{Choice, ChoiceOption, Decider, DecisionRecord, IllegalChoice, Table};
use ti4_engine::fingerprint::{CanonicalHash, CanonicalHashVersion, decision_hash};
use ti4_engine::game::Game;
use ti4_model::state::GameState;

#[derive(Debug, Error)]
pub enum ReplayError {
    #[error("Engine error during replay: {0}")]
    EngineError(String),
    #[error("Replay script diverged at decision {step}: expected {expected}, offered {offered:?}")]
    Diverged {
        step: usize,
        expected: String,
        offered: Vec<String>,
    },
    #[error("Engine required more decisions ({actual}) than recorded in log ({expected})")]
    ExcessDecisions { expected: usize, actual: usize },
}

#[derive(Debug, Clone, PartialEq)]
pub struct ReplayReport {
    pub decision_count: usize,
    pub original_hashes: Vec<CanonicalHash>,
    pub replayed_hashes: Vec<CanonicalHash>,
    pub hashes_match: bool,
    pub final_state: GameState,
}

struct ReplayDecider {
    script: VecDeque<String>,
    #[allow(dead_code)]
    step_index: usize,
}

impl Decider for ReplayDecider {
    fn choose(&mut self, choice: &Choice) -> Result<ChoiceOption, IllegalChoice> {
        self.step_index += 1;

        let Some(wanted) = self.script.pop_front() else {
            return Err(IllegalChoice::DeciderFailed {
                player: choice.player.clone(),
                prompt: choice.prompt.clone(),
                reason: "replay completed all scripted decisions".to_owned(),
            });
        };

        let offered: Vec<String> = choice.options.iter().map(|o| o.id.clone()).collect();
        if let Some(opt) = choice.options.iter().find(|o| o.id == wanted) {
            Ok(opt.clone())
        } else {
            Err(IllegalChoice::ScriptDiverged {
                player: choice.player.clone(),
                wanted,
                offered,
            })
        }
    }
}

/// Replays a game from its initial state and galaxy given a slice of accepted decision records.
///
/// Returns a [`ReplayReport`] comparing the canonical hashes of the original decision log
/// with the canonical hashes generated by replaying the game step-by-step.
///
/// # Errors
///
/// Returns [`ReplayError`] if the engine fails or decisions diverge.
pub fn replay_session(
    initial_state: &GameState,
    galaxy: Option<&Galaxy>,
    records: &[DecisionRecord],
) -> Result<ReplayReport, ReplayError> {
    let original_hashes: Vec<CanonicalHash> = records
        .iter()
        .map(|r| decision_hash(CanonicalHashVersion::V1, r))
        .collect();

    let choices: VecDeque<String> = records.iter().map(|r| r.chosen.clone()).collect();
    let decider = Box::new(ReplayDecider {
        script: choices,
        step_index: 0,
    });
    let table = Table::with_default(decider);

    let mut game = Game::with_table(initial_state.clone(), ContentStore::embedded(), table);
    if let Some(g) = galaxy {
        game = game.with_galaxy(g.clone());
    }

    // Step until all recorded decisions are replayed
    while game.table.log.records.len() < records.len() {
        let result = game.step();
        if let Some(err) = result.error {
            let err_str = err.to_string();
            if err_str.contains("replay completed all scripted decisions") {
                break;
            }
            return Err(ReplayError::EngineError(err_str));
        }
        if result.finished && game.table.log.records.len() < records.len() {
            return Err(ReplayError::EngineError(
                "Game finished before all recorded decisions could be replayed".to_owned(),
            ));
        }
    }

    let replayed_hashes: Vec<CanonicalHash> = game
        .table
        .log
        .records
        .iter()
        .map(|r| decision_hash(CanonicalHashVersion::V1, r))
        .collect();

    let hashes_match = replayed_hashes == original_hashes;

    Ok(ReplayReport {
        decision_count: game.table.log.records.len(),
        original_hashes,
        replayed_hashes,
        hashes_match,
        final_state: game.state,
    })
}
